In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import os
%matplotlib inline

In [2]:
os.getcwd()

'/Users/zhengyuanrui/Decoding_SALT/Decode_SALT/1_Script/2_model'

In [3]:
os.chdir("../../3_Result")

In [6]:
df_noref = pd.read_csv("/Users/zhengyuanrui/Decoding_SALT/Decode_SALT/2_Data/df_no_ref.csv")
df_selfref = pd.read_csv("/Users/zhengyuanrui/Decoding_SALT/Decode_SALT/2_Data/df_self_ref.csv")

In [5]:
coef_within_no_current = np.load("1_Logistic/1_Current/coef_no_current.npy")

In [12]:
coef_cross12_no_tb =np.load("1_Logistic/2_Trials-Back/coef_cross1.npy")


In [13]:
coef_cross12_no_tb.shape

(195, 3, 24)

In [7]:
coef_within_no_current.shape

(164, 3, 3)

In [25]:
sub, model, feature = coef_within_no_current.shape

In [38]:
df_result = dict(subID=[], model=[], feature1=[], feature2=[], feature3=[])
for i in range(sub):
    df_result["subID"].append(i)
    df_result["subID"].append(i)
    df_result["subID"].append(i)
    onesub = coef_within_no_current[i]
    for j in range(model):
        df_result["model"].append(j)
        onemodel = onesub[j]
        df_result["feature1"].append(onemodel[0])
        df_result["feature2"].append(onemodel[1])
        df_result["feature3"].append(onemodel[2])
df = pd.DataFrame(df_result)
df

subID  model  feature1  feature2      feature3
0        0      0  0.000698 -0.000392 -8.616008e-07
1        0      1 -0.000391  0.000155 -2.449219e-05
2        0      2 -0.000307  0.000237  2.550199e-05
3        1      0  0.000699 -0.000393  2.282463e-06
4        1      1 -0.000394  0.000153 -2.381244e-05
..     ...    ...       ...       ...           ...
487    162      1 -0.000398  0.000151 -2.215689e-05
488    162      2 -0.000295  0.000235  2.135495e-05
489    163      0  0.000702 -0.000390  3.257805e-06
490    163      1 -0.000408  0.000157 -2.429492e-05
491    163      2 -0.000293  0.000234  2.117622e-05

[492 rows x 5 columns]

In [39]:
coef_within_no_current

array([[[ 6.98077564e-04, -3.92290781e-04, -8.61600808e-07],
        [-3.91079097e-04,  1.55439732e-04, -2.44921859e-05],
        [-3.06753055e-04,  2.37042412e-04,  2.55019901e-05]],

       [[ 6.98657838e-04, -3.92602752e-04,  2.28246313e-06],
        [-3.93991789e-04,  1.53404544e-04, -2.38124352e-05],
        [-3.04426581e-04,  2.39384700e-04,  2.16746648e-05]],

       [[ 7.00511764e-04, -3.92404924e-04,  1.13712899e-07],
        [-3.96154655e-04,  1.54663954e-04, -2.44726317e-05],
        [-3.04118171e-04,  2.37927183e-04,  2.45033040e-05]],

       ...,

       [[ 6.95972772e-04, -3.89930045e-04, -5.32935288e-07],
        [-3.91025949e-04,  1.54733120e-04, -2.26770839e-05],
        [-3.04716285e-04,  2.35377339e-04,  2.33496113e-05]],

       [[ 6.93587079e-04, -3.85902233e-04,  9.42775668e-07],
        [-3.97890939e-04,  1.51190582e-04, -2.21568889e-05],
        [-2.95463348e-04,  2.34892899e-04,  2.13549547e-05]],

       [[ 7.01806538e-04, -3.90479438e-04,  3.25780539e-06],
 

In [37]:
coef_within_no_current

array([[[ 6.98077564e-04, -3.92290781e-04, -8.61600808e-07],
        [-3.91079097e-04,  1.55439732e-04, -2.44921859e-05],
        [-3.06753055e-04,  2.37042412e-04,  2.55019901e-05]],

       [[ 6.98657838e-04, -3.92602752e-04,  2.28246313e-06],
        [-3.93991789e-04,  1.53404544e-04, -2.38124352e-05],
        [-3.04426581e-04,  2.39384700e-04,  2.16746648e-05]],

       [[ 7.00511764e-04, -3.92404924e-04,  1.13712899e-07],
        [-3.96154655e-04,  1.54663954e-04, -2.44726317e-05],
        [-3.04118171e-04,  2.37927183e-04,  2.45033040e-05]],

       ...,

       [[ 6.95972772e-04, -3.89930045e-04, -5.32935288e-07],
        [-3.91025949e-04,  1.54733120e-04, -2.26770839e-05],
        [-3.04716285e-04,  2.35377339e-04,  2.33496113e-05]],

       [[ 6.93587079e-04, -3.85902233e-04,  9.42775668e-07],
        [-3.97890939e-04,  1.51190582e-04, -2.21568889e-05],
        [-2.95463348e-04,  2.34892899e-04,  2.13549547e-05]],

       [[ 7.01806538e-04, -3.90479438e-04,  3.25780539e-06],
 

In [24]:
coef_within_no_current

for i, j in range

array([[[ 6.98077564e-04, -3.92290781e-04, -8.61600808e-07],
        [-3.91079097e-04,  1.55439732e-04, -2.44921859e-05],
        [-3.06753055e-04,  2.37042412e-04,  2.55019901e-05]],

       [[ 6.98657838e-04, -3.92602752e-04,  2.28246313e-06],
        [-3.93991789e-04,  1.53404544e-04, -2.38124352e-05],
        [-3.04426581e-04,  2.39384700e-04,  2.16746648e-05]],

       [[ 7.00511764e-04, -3.92404924e-04,  1.13712899e-07],
        [-3.96154655e-04,  1.54663954e-04, -2.44726317e-05],
        [-3.04118171e-04,  2.37927183e-04,  2.45033040e-05]],

       ...,

       [[ 6.95972772e-04, -3.89930045e-04, -5.32935288e-07],
        [-3.91025949e-04,  1.54733120e-04, -2.26770839e-05],
        [-3.04716285e-04,  2.35377339e-04,  2.33496113e-05]],

       [[ 6.93587079e-04, -3.85902233e-04,  9.42775668e-07],
        [-3.97890939e-04,  1.51190582e-04, -2.21568889e-05],
        [-2.95463348e-04,  2.34892899e-04,  2.13549547e-05]],

       [[ 7.01806538e-04, -3.90479438e-04,  3.25780539e-06],
 

In [16]:
m,n,r = coef_within_no_current.shape
out_arr = np.column_stack((np.repeat(np.arange(m), n), coef_within_no_current.reshape(m*n, -1)))

In [18]:
out_df = pd.DataFrame(out_arr, columns=["id", "m", "f"])
out_df

ValueError: Shape of passed values is (492, 4), indices imply (492, 3)

In [8]:
coef_within_no_current

array([[[ 6.98077564e-04, -3.92290781e-04, -8.61600808e-07],
        [-3.91079097e-04,  1.55439732e-04, -2.44921859e-05],
        [-3.06753055e-04,  2.37042412e-04,  2.55019901e-05]],

       [[ 6.98657838e-04, -3.92602752e-04,  2.28246313e-06],
        [-3.93991789e-04,  1.53404544e-04, -2.38124352e-05],
        [-3.04426581e-04,  2.39384700e-04,  2.16746648e-05]],

       [[ 7.00511764e-04, -3.92404924e-04,  1.13712899e-07],
        [-3.96154655e-04,  1.54663954e-04, -2.44726317e-05],
        [-3.04118171e-04,  2.37927183e-04,  2.45033040e-05]],

       ...,

       [[ 6.95972772e-04, -3.89930045e-04, -5.32935288e-07],
        [-3.91025949e-04,  1.54733120e-04, -2.26770839e-05],
        [-3.04716285e-04,  2.35377339e-04,  2.33496113e-05]],

       [[ 6.93587079e-04, -3.85902233e-04,  9.42775668e-07],
        [-3.97890939e-04,  1.51190582e-04, -2.21568889e-05],
        [-2.95463348e-04,  2.34892899e-04,  2.13549547e-05]],

       [[ 7.01806538e-04, -3.90479438e-04,  3.25780539e-06],
 

In [14]:
coef_cross12_no_tb

array([[[-1.36194353e-04,  4.73699412e-05,  6.49633731e-05, ...,
         -1.20860488e-03,  7.56181638e-04,  4.53305813e-04],
        [ 5.56046752e-05, -3.34101017e-05, -1.89879352e-05, ...,
          6.08150625e-04,  6.36222517e-04, -1.24447173e-03],
        [ 8.05783986e-05, -1.39681421e-05, -4.59819928e-05, ...,
          6.00448324e-04, -1.39240941e-03,  7.91163886e-04]],

       [[-1.36194353e-04,  4.73699412e-05,  6.49633731e-05, ...,
         -1.20860488e-03,  7.56181638e-04,  4.53305813e-04],
        [ 5.56046752e-05, -3.34101017e-05, -1.89879352e-05, ...,
          6.08150625e-04,  6.36222517e-04, -1.24447173e-03],
        [ 8.05783986e-05, -1.39681421e-05, -4.59819928e-05, ...,
          6.00448324e-04, -1.39240941e-03,  7.91163886e-04]],

       [[-1.36194353e-04,  4.73699412e-05,  6.49633731e-05, ...,
         -1.20860488e-03,  7.56181638e-04,  4.53305813e-04],
        [ 5.56046752e-05, -3.34101017e-05, -1.89879352e-05, ...,
          6.08150625e-04,  6.36222517e-04, -1.244